name: Deploy Infrastructure

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TF_LOG: INFO
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_ACTION_WORKING_DIR: 'terraform'
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_deployment_env: 'Sandbox'
  TF_VAR_sqlsvr_server_name: 'mer-sql-4.database.windows.net'
  TF_VAR_sqlsvr_server_db: 'mercrm1-dev'
  TF_VAR_sqlsvr_username: ${{ secrets.SQLSVR_USERNAME }}
  TF_VAR_sqlsvr_password: ${{ secrets.SQLSVR_PASSWORD }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v2

    # Install
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.0

    # Initialize
    - name: Terraform Init
      id: init
      run: terraform init

    # Validate
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
      # Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
